services:
  api:
    build: ./backend
    container_name: whoami-api
    env_file:
     - .env
    ports:
     - "${APP_PORT}:8000"
    volumes:
      - whoami_data:/data
    restart: unless-stopped

  bot:
    build: ./bot
    container_name: whoami-bot
    env_file: .env
    depends_on:
      - api
  
  whoami-ai:
    build: ./backend/ai-service
    env_file: .env
    environment:
     - GROQ_API_KEY=${GROQ_API_KEY}
    ports:
     - "8001:8001"
    restart: unless-stopped

volumes:
  whoami_data:
